services:
  db:
    image: "postgis/postgis:15-3.4-alpine"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "0269306032DbB"
      POSTGRES_DB: "routing"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

